CC := gcc

CFLAGS += -std=c17
CFLAGS += -fPIC
CFLAGS += -gdwarf-4
CFLAGS += -Wall
CFLAGS += -Wextra
CFLAGS += -Wwrite-strings
CFLAGS += -Wno-parentheses
CFLAGS += -Wpedantic
CFLAGS += -Warray-bounds
CFLAGS += -Wconversion
CFLAGS += -Wstrict-prototypes
CFLAGS += -fanalyzer
